"""schema inicial multi-tenant

Revision ID: 0002_initial_schema
Revises: 0001_pgvector
Create Date: 2026-07-30 16:31:55.967149+00:00

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002_initial_schema'
down_revision: str | None = '0001_pgvector'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'TIME_ENTRY', 'REVIEW', 'CONSENT_GRANTED', 'CONSENT_REVOKED', name='audit_action', native_enum=False, length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_tenant_entity', 'audit_logs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('sites',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_sites_tenant_name')
    )
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'HR', 'VIEWER', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('beacons',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('protocol', sa.Enum('IBEACON', 'EDDYSTONE', name='beacon_protocol', native_enum=False, length=20), nullable=False),
    sa.Column('ibeacon_uuid', sa.String(length=36), nullable=True),
    sa.Column('ibeacon_major', sa.Integer(), nullable=True),
    sa.Column('ibeacon_minor', sa.Integer(), nullable=True),
    sa.Column('eddystone_namespace', sa.String(length=20), nullable=True),
    sa.Column('eddystone_instance', sa.String(length=12), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('min_rssi', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'protocol', 'ibeacon_uuid', 'ibeacon_major', 'ibeacon_minor', 'eddystone_namespace', 'eddystone_instance', name='uq_beacons_tenant_identifier')
    )
    op.create_index(op.f('ix_beacons_tenant_id'), 'beacons', ['tenant_id'], unique=False)
    op.create_index('ix_beacons_tenant_site', 'beacons', ['tenant_id', 'site_id', 'is_active'], unique=False)
    op.create_table('employees',
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='employee_status', native_enum=False, length=20), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('terminated_at', sa.Date(), nullable=True),
    sa.Column('default_site_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cpf', name='uq_employees_tenant_cpf'),
    sa.UniqueConstraint('tenant_id', 'external_code', name='uq_employees_tenant_code')
    )
    op.create_index(op.f('ix_employees_external_code'), 'employees', ['external_code'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('wifi_networks',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('ssid', sa.String(length=64), nullable=False),
    sa.Column('bssid', sa.String(length=17), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bssid', name='uq_wifi_tenant_bssid')
    )
    op.create_index(op.f('ix_wifi_networks_tenant_id'), 'wifi_networks', ['tenant_id'], unique=False)
    op.create_index('ix_wifi_tenant_site', 'wifi_networks', ['tenant_id', 'site_id', 'is_active'], unique=False)
    op.create_table('consents',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('BIOMETRIC', 'LOCATION', name='consent_type', native_enum=False, length=20), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('policy_text_hash', sa.String(length=64), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_tenant_employee', 'consents', ['tenant_id', 'employee_id', 'consent_type'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', name='device_platform', native_enum=False, length=20), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=30), nullable=True),
    sa.Column('push_token', sa.String(length=500), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_fingerprint', name='uq_devices_tenant_fingerprint')
    )
    op.create_index(op.f('ix_devices_employee_id'), 'devices', ['employee_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('face_templates',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('source_image_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_templates_tenant_employee', 'face_templates', ['tenant_id', 'employee_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_face_templates_tenant_id'), 'face_templates', ['tenant_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('IN', 'OUT', 'BREAK_START', 'BREAK_END', name='entry_type', native_enum=False, length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('matched_face_template_id', sa.UUID(), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('selfie_image_key', sa.String(length=500), nullable=True),
    sa.Column('location_method', sa.Enum('BEACON', 'WIFI', 'GPS', 'NONE', name='location_method', native_enum=False, length=20), nullable=False),
    sa.Column('location_confidence', sa.Float(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('beacon_id', sa.UUID(), nullable=True),
    sa.Column('wifi_network_id', sa.UUID(), nullable=True),
    sa.Column('beacon_rssi', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('distance_to_site_m', sa.Float(), nullable=True),
    sa.Column('location_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING_REVIEW', 'REJECTED', name='time_entry_status', native_enum=False, length=20), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beacon_id'], ['beacons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_face_template_id'], ['face_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wifi_network_id'], ['wifi_networks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_time_entries_idempotency')
    )
    op.create_index('ix_time_entries_tenant_employee_time', 'time_entries', ['tenant_id', 'employee_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant_id'), 'time_entries', ['tenant_id'], unique=False)
    op.create_index('ix_time_entries_tenant_status', 'time_entries', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_time_entries_tenant_time', 'time_entries', ['tenant_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_entries_tenant_time', table_name='time_entries')
    op.drop_index('ix_time_entries_tenant_status', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_tenant_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_tenant_employee_time', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_face_templates_tenant_id'), table_name='face_templates')
    op.drop_index('ix_face_templates_tenant_employee', table_name='face_templates')
    op.drop_table('face_templates')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_employee_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index('ix_consents_tenant_employee', table_name='consents')
    op.drop_table('consents')
    op.drop_index('ix_wifi_tenant_site', table_name='wifi_networks')
    op.drop_index(op.f('ix_wifi_networks_tenant_id'), table_name='wifi_networks')
    op.drop_table('wifi_networks')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_external_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_beacons_tenant_site', table_name='beacons')
    op.drop_index(op.f('ix_beacons_tenant_id'), table_name='beacons')
    op.drop_table('beacons')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_audit_tenant_entity', table_name='audit_logs')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
