"""config de batida de ponto

Cria a configuracao por empresa (observacao e rotulo) e os dois campos que ela
alimenta no registro de ponto.

Nao ha backfill: ausencia de linha em punch_configs significa o padrao — ponto
simples, sem campo nenhum —, que e exatamente o comportamento de quem ja usa o
sistema. Nenhum registro existente muda.

Revision ID: 0005_punch_config
Revises: 0004_beacon_mac
Create Date: 2026-08-03 10:48:29.448039+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005_punch_config'
down_revision: str | None = '0004_beacon_mac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punch_configs',
    sa.Column('note_mode', sa.Enum('hidden', 'optional', 'required', name='note_mode', native_enum=False, length=20), nullable=False),
    sa.Column('note_prompt', sa.String(length=120), nullable=True),
    sa.Column('label_mode', sa.Enum('hidden', 'free', 'list', name='label_mode', native_enum=False, length=20), nullable=False),
    sa.Column('label_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_punch_configs_tenant')
    )
    op.create_index(op.f('ix_punch_configs_tenant_id'), 'punch_configs', ['tenant_id'], unique=False)
    op.create_table('punch_labels',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('entry_type', sa.Enum('in', 'out', 'break_start', 'break_end', name='entry_type', native_enum=False, length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['punch_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_punch_labels_tenant_name')
    )
    op.create_index(op.f('ix_punch_labels_config_id'), 'punch_labels', ['config_id'], unique=False)
    op.create_index(op.f('ix_punch_labels_tenant_id'), 'punch_labels', ['tenant_id'], unique=False)
    op.add_column('time_entries', sa.Column('label', sa.String(length=60), nullable=True))
    op.add_column('time_entries', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'note')
    op.drop_column('time_entries', 'label')
    op.drop_index(op.f('ix_punch_labels_tenant_id'), table_name='punch_labels')
    op.drop_index(op.f('ix_punch_labels_config_id'), table_name='punch_labels')
    op.drop_table('punch_labels')
    op.drop_index(op.f('ix_punch_configs_tenant_id'), table_name='punch_configs')
    op.drop_table('punch_configs')
    # ### end Alembic commands ###
